apiVersion: v1
kind: Namespace
metadata:
  name: teststage
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: teststage-sa
  namespace: teststage
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: teststage-sa-role
  namespace: teststage
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "get", "list", "watch", "delete"]

  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]

  - apiGroups: [""]
    resources: ["pods/attach"]
    verbs: ["create"]

  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]

  - apiGroups: [""]
    resources: ["pods/portforward"]
    verbs: ["create"]

  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: teststage-sa-rb
  namespace: teststage
subjects:
  - kind: ServiceAccount
    name: teststage-sa
    namespace: teststage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: teststage-sa-role
